In [1]:
import shogi
from shogi import CSA

In [2]:
path = "/Users/JP26965/private/shogi_ai/data/kifu_csa/2017/wdoor+floodgate-300-10F+sg_test03a+Shocking_Blue_Incinerator+20171123113007.csa"
kifu = shogi.CSA.Parser.parse_file(path)[0]
kifu

{'names': ['sg_test03a', 'Shocking_Blue_Incinerator'],
 'sfen': 'lnsgkgsnl/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSNL b - 1',
 'moves': ['7g7f',
  '3c3d',
  '2g2f',
  '5c5d',
  '2f2e',
  '8b5b',
  '3i4h',
  '5d5e',
  '5i6h',
  '2b3c',
  '3g3f',
  '5a6b',
  '4h3g',
  '6b7b',
  '3g4f',
  '7b8b',
  '6h7h',
  '7a7b',
  '7i6h',
  '3a4b',
  '4f4e',
  '4a3b',
  '4e3d',
  '3c4d',
  '2e2d',
  '2c2d',
  '2h2d',
  'P*2b',
  '2d2h',
  '5e5f',
  '8h4d',
  '4c4d',
  '5g5f',
  'B*6d',
  '2h1h',
  '9c9d',
  '9g9f',
  '5b5c',
  '6g6f',
  '3b2c',
  '6f6e',
  '6d1i+',
  '1h1i',
  '2c3d',
  'B*7e',
  '6c6d',
  '6e6d',
  'L*6b',
  '1i1h',
  '5c2c',
  'P*2h',
  '3d4e',
  'B*3b',
  '4e5f',
  'P*5g',
  '5f4g',
  '7h8h',
  'P*5b',
  '9f9e',
  '9d9e',
  '3b2a+',
  '7c7d',
  '2a6e',
  '7d7e',
  'N*7d',
  '8b7a',
  '6e4g',
  'S*7c',
  '7d6b+',
  '6a6b',
  'L*6f',
  'P*6e',
  '4g6e',
  '4b5c',
  '6e5f',
  'B*4e',
  '5f4g',
  'P*3e',
  'G*4f',
  '4e5d',
  '4g5f',
  '7e7f',
  'P*7d',
  '7c6d',
  '6f6d',
  '5c6d

In [3]:
board = shogi.Board()
for idx, move in enumerate(kifu['moves']):
    board.push_usi(move)

In [4]:
board.zobrist_hash()

7098524613128195808

In [9]:
from functools import reduce
import operator
x = [1, 3, 4]
reduce(operator.add, x)

8

In [6]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [7]:
import numpy as np
np.ones((9, 9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
import torch
import torch.nn as nn
input = torch.ones(2, 3)
input

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [22]:
m = nn.LogSoftmax(dim=0)
output = m(input)
output

tensor([[-0.6931, -0.6931, -0.6931],
        [-0.6931, -0.6931, -0.6931]])

In [20]:
torch.exp(torch.tensor([1.09]))

tensor([2.9743])

In [23]:
torch.exp(torch.tensor([0.6931]))

tensor([1.9999])